
#' Create interactive map of emission risk scores
#'
#' @description
#' Generates an interactive leaflet map displaying emission risk scores for countries
#' around the world. The map shows country-level emission risk scores with detailed
#' hover information including component scores for epidemiological status, surveillance,
#' control measures, commerce, and data source.
#'
#' @param emission_risk A data frame containing emission risk data with the following required columns:
#'   - `iso3`: 3-letter ISO country codes
#'   - `emission_risk`: Overall emission risk score (0-12)
#'   - `sc_epistatus`: Epidemiological status score (0-3)
#'   - `sc_survmeasures`: Surveillance measures score (0-2)
#'   - `sc_control`: Control measures score (0-3)
#'   - `sc_commerce`: Commerce score (0-4)
#'   - `data_source`: Source of the data for each country
#'   This data frame is typically generated by [calc_emission_risk()].
#' @param ll A leaflet map object to add the emission risk layer to.
#'   Defaults to [basemap()] which provides a standard base map with tile layers.
#'   Intended mainly for use with leafletProxy in the RiskIntro App.
#'
#' @return An interactive leaflet map object displaying emission risk scores with:
#'   - Country polygons colored by emission risk score using viridis color scale
#'   - Interactive hover labels showing detailed risk component breakdown
#'   - Legend showing emission risk score scale (0-12)
#'   - Base map layers for geographic context
#'
#' @details
#' The map visualization displays emission risk scores on a 0-12 scale using a viridis
#' color palette (reversed so higher risk = warmer colors). Each country polygon shows
#' detailed information on hover including:
#'
#' - Overall emission risk score (0-12)
#' - Component scores: epidemiological status (0-3), surveillance (0-2),
#'   control measures (0-3), commerce (0-4)
#' - Data source information
#'
#' Countries are colored based on their total emission risk score, with countries
#' lacking data shown in grey. The map includes standard leaflet controls for
#' zooming and panning, plus layer controls for switching between base map styles.
#'
#' @examples
#' \dontrun{
#' # Create emission risk data
#' emission_rf <- bind_rows(
#'   erf_row(iso3 = "TUN", country = "Tunisia", epistatus = 0,
#'           survmeasures = c("Active surveillance", "Passive surveillance"),
#'           control = c("Border control", "Culling at outbreak sites"),
#'           commerce = "Legal trade"),
#'   erf_row(iso3 = "DZA", country = "Algeria", epistatus = 2,
#'           survmeasures = c("Passive surveillance"),
#'           control = c("Movement zoning and restrictions"),
#'           commerce = "No trade")
#' )
#'
#' # Calculate emission risk scores
#' emission_risk <- calc_emission_risk(emission_rf)
#'
#' # Create interactive map
#' plot_emission_risk_interactive(emission_risk)
#'
#' # Add to existing map
#' my_map <- basemap()
#' plot_emission_risk_interactive(emission_risk, ll = my_map)
#' }
#'
#' @seealso
#' - [plot_emission_risk()]
#' - [calc_emission_risk()] for calculating emission risk scores
#' - [basemap()] for creating base leaflet maps
#' - [riskintrodata::erf_row()] for creating emission risk factor data
#'
#' @export
#' @importFrom leaflet addLegend addPolygons colorBin highlightOptions
plot_emission_risk_interactive <- function(
    emission_risk,
    ll = basemap()
) {
  er_sf <- riskintrodata::world_sf |>
    left_join(
      emission_risk,
      by = "iso3"
    )
  pal <- ll_scale(c(0, 12))
  label_content <- map(
    paste0(
      '<h4 style="margin: 0 0 8px 0; font-weight: bold;">', er_sf$country_name, '</h4>',
      '<table style="border-collapse: collapse; width: 100%; font-size: 12px;">',
      '<tr><td style="padding: 3px 8px; border-bottom: 1px solid #ddd;"><strong>Emission risk</strong></td><td style="padding: 3px 8px; border-bottom: 1px solid #ddd;">', fmt_num(er_sf$emission_risk), '/12</td></tr>',
      '<tr><td style="padding: 3px 8px; border-bottom: 1px solid #ddd;"><strong>Epistatus</strong></td><td style="padding: 3px 8px; border-bottom: 1px solid #ddd;">', fmt_num(er_sf$sc_epistatus), '/3</td></tr>',
      '<tr><td style="padding: 3px 8px; border-bottom: 1px solid #ddd;"><strong>Surveillance</strong></td><td style="padding: 3px 8px; border-bottom: 1px solid #ddd;">', fmt_num(er_sf$sc_survmeasures), '/2</td></tr>',
      '<tr><td style="padding: 3px 8px; border-bottom: 1px solid #ddd;"><strong>Control</strong></td><td style="padding: 3px 8px; border-bottom: 1px solid #ddd;">', fmt_num(er_sf$sc_control), '/3</td></tr>',
      '<tr><td style="padding: 3px 8px; border-bottom: 1px solid #ddd;"><strong>Commerce</strong></td><td style="padding: 3px 8px; border-bottom: 1px solid #ddd;">', fmt_num(er_sf$sc_commerce), '/4</td></tr>',
      '<tr><td style="padding: 3px 8px;"><em>Source</em></td><td style="padding: 3px 8px;"><em>', er_sf$data_source, '</em></td></tr>',
      '</table>'
    ),
    HTML
  )

  # ll <- basemap() # for dev
  ll <- ll |>
    addPolygons(
      data = er_sf,
      fillColor = ~pal(er_sf$emission_risk),
      weight = 2,
      opacity = 1,
      color = "white",
      dashArray = "3",
      fillOpacity = 0.7,
      label = label_content,
      layerId = er_sf$iso3,
      highlightOptions = highlightOptions(
        weight = 5,
        color = "#666",
        dashArray = "",
        fillOpacity = 0.7,
        bringToFront = TRUE
      ),
      labelOptions = riLabelOptions()
    )
  ll <- ll |> ll_legend(
    pal = pal,
    scale = c(0, 12),
    title = "Emission risk score"
  )
  ll
}

#' Create static map of emission risk scores
#'
#' @description
#' Generates a static ggplot2 map displaying emission risk scores for countries
#' around the world. The map shows country-level emission risk scores using
#' a viridis color scale without interactive features.
#'
#' @param emission_risk A data frame containing emission risk data with the following required columns:
#'   - `iso3`: 3-letter ISO country codes
#'   - `emission_risk`: Overall emission risk score (0-12)
#'   This data frame is typically generated by [calc_emission_risk()].
#'
#' @return A ggplot2 object displaying emission risk scores with:
#'   - Country polygons colored by emission risk score using viridis color scale
#'   - Legend showing emission risk score scale (0-12)
#'   - Clean map theme without axis labels or grid lines
#'
#' @details
#' The map visualization displays emission risk scores on a 0-12 scale using a viridis
#' color palette (reversed so higher risk = warmer colors). Countries lacking data
#' are shown in grey. This is the static version of [plot_emission_risk_interactive()].
#'
#' @examples
#' \dontrun{
#' # Create emission risk data
#' emission_rf <- bind_rows(
#'   erf_row(iso3 = "TUN", country = "Tunisia", epistatus = 0,
#'           survmeasures = c("Active surveillance", "Passive surveillance"),
#'           control = c("Border control", "Culling at outbreak sites"),
#'           commerce = "Legal trade"),
#'   erf_row(iso3 = "DZA", country = "Algeria", epistatus = 2,
#'           survmeasures = c("Passive surveillance"),
#'           control = c("Movement zoning and restrictions"),
#'           commerce = "No trade")
#' )
#'
#' # Calculate emission risk scores
#' emission_risk <- calc_emission_risk(emission_rf)
#'
#' # Create static map
#' plot_emission_risk(emission_risk)
#' }
#' @seealso
#' - [plot_emission_risk_interactive()] for interactive version
#' - [calc_emission_risk()] for calculating emission risk scores
#' - [riskintrodata::erf_row()] for creating emission risk factor data
#'
#' @export
#' @importFrom ggplot2 ggplot geom_sf aes theme_void scale_fill_viridis_c
plot_emission_risk <- function(emission_risk) {
  er_sf <- riskintrodata::world_sf |>
    left_join(
      emission_risk,
      by = "iso3"
    )
  gg <- ggplot()
  gg <- gg +
    geom_sf(
      data = er_sf,
      aes(fill = .data$emission_risk)
    )
  gg <- gg +
    scale_fill_viridis_c(
      limits = c(0, 12),
      direction = -1,
      name = "Emission risk\nscore",
      na.value = "grey90"
    )
  gg <- gg + theme_void()
  gg
}
